name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Jekyll site with Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/jekyll:latest \
          jekyll build

    - name: Upload generated site as artifact
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site
